# Carregar um classificador já treinado

In [ ]:
rede_neural = pickle.load(open('rede_neural_finalizado.sav', 'rb'))
arvore = pickle.load(open('arvore_finalizado.sav', 'rb'))
svm = pickle.load(open('svm_finalizado.sav', 'rb'))

In [ ]:
novo_registro = X_credit[1999]
novo_registro

array([-1.03572293, -0.93978122,  0.04244312])

In [ ]:
novo_registro.shape

(3,)

In [ ]:
novo_registro = novo_registro.reshape(1, -1)
novo_registro.shape

(1, 3)

In [ ]:
novo_registro

array([[-1.03572293, -0.93978122,  0.04244312]])

In [ ]:
rede_neural.predict(novo_registro)

array([1])

In [ ]:
arvore.predict(novo_registro)

array([1])

In [ ]:
svm.predict(novo_registro)

array([1])

# Combinação de classificadores



In [ ]:
novo_registro = X_credit[0]
novo_registro = novo_registro.reshape(1, -1)
novo_registro, novo_registro.shape # para colocar em formato de matriz

(array([[-1.3754462 ,  0.50631087,  0.10980934]]), (1, 3))

In [ ]:
resposta_rede_neural = rede_neural.predict(novo_registro)
resposta_arvore = arvore.predict(novo_registro)
resposta_svm = svm.predict(novo_registro)

In [ ]:
resposta_rede_neural[0], resposta_arvore[0], resposta_svm[0]
# o retorno indica a classe, os 3 algoritmos retornaram a mesma classificação para uma mesma feature

(0, 0, 0)

In [ ]:
# contagem de quantos classificadores gera a classe 0 (paga o emprestimo) e classe 1  (não paga o emprestimo)
paga = 0
nao_paga = 1

if resposta_rede_neural[0] == 1:
  nao_paga += 1
else:
  paga += 1

if resposta_arvore[0] == 1:
  nao_paga += 1
else:
  paga += 1

if resposta_svm[0] == 1:
  nao_paga += 1
else:
  paga += 1

if paga > nao_paga:
  print("Cliente pagará o empréstimo")
elif paga == nao_paga:
  print("Empate")
else:
  print("Cliente não pagará o empréstimo")

Cliente pagará o empréstimo


# Rejeição de classificadores

In [ ]:
novo_registro = X_credit[0]
novo_registro = novo_registro.reshape(1, -1)
novo_registro, novo_registro.shape

# retorna dados do cliente
# primeiro atributo renda = -1.3754462
# segundo atributo idade = 0.50631087
# terceiro atributo divida = 0.10980934

(array([[-1.3754462 ,  0.50631087,  0.10980934]]), (1, 3))

In [ ]:
resposta_rede_neural = rede_neural.predict(novo_registro)
resposta_arvore = arvore.predict(novo_registro) # metodo predict retorna somente a classe
resposta_svm = svm.predict(novo_registro)

In [ ]:
resposta_rede_neural[0], resposta_arvore[0], resposta_svm[0]

(0, 0, 0)

#### Confiança para Rede_neural

In [ ]:
# para a REJEIÇÃO precisamos extrair a PROBABILIDADE

# criação da variação probabilidade_rede_neural
probabilidade_rede_neural = rede_neural.predict_proba(novo_registro) # metodo predict_proba que vai passar o novo_registro como argumento
probabilidade_rede_neural

# retorna uma probabilidade para a classe 0 (1.00000000e+00) e outra pra a classe 1 (6.72352972e-17)

array([[1.00000000e+00, 6.72352972e-17]])

In [ ]:
# buscar o maior valor de probabilidade que foi previsto

confianca_rede_neural = probabilidade_rede_neural.max()
confianca_rede_neural

# retorno é 0.9999999999999999 de chances de um registro que paga o emprestimo

0.9999999999999999

#### Confiança para arvore de decisão

In [ ]:
probabilidade_arvore = arvore.predict_proba(novo_registro)
confianca_arvore = probabilidade_arvore.max()
confianca_arvore

1.0

#### Confiança para SVM

In [ ]:
probabilidade_svm = svm.predict_proba(novo_registro)
confianca_svm = probabilidade_svm.max()
confianca_svm

0.9999972331211946

#### Rejeição: adicionar um parametro de confiança minina desejada

In [ ]:
paga = 0
nao_paga = 0
confianca_minima = 0.999999
algoritmos = 0

if confianca_rede_neural >= confianca_minima:
  algoritmos += 1
  if resposta_rede_neural[0] == 1:
    nao_paga += 1
  else:
    paga += 1

if confianca_arvore >= confianca_minima:
  algoritmos += 1
  if resposta_arvore[0] == 1:
    nao_paga += 1
  else:
    paga += 1

if confianca_svm >= confianca_minima:
  algoritmos += 1
  if resposta_svm[0] == 1:
    nao_paga += 1
  else:
    paga += 1

if paga > nao_paga:
  print('Cliente pagará o empréstimo, baseado em {} algoritmos'.format(algoritmos))
elif paga == nao_paga:
  print('Empate, baseado em {} algoritmos'.format(algoritmos))
else:
  print('Cliente não pagará o empréstimo, baseado em {} algoritmos'.format(algoritmos))

Cliente pagará o empréstimo, baseado em 2 algoritmos
